# Centralized qox (prod) config – typically overridden by wrapper flags

projects = { "/home/bhd" = { trust_level = "trusted" } }

[mcp_servers.context7]
args = ["-y", "@upstash/context7-mcp", "--api-key", "ctx7sk-f7184878-4319-4071-83f4-af7cabcb83cd"]
command = "npx"

[mcp_servers.playwright]
command = "npx"
args = ["@playwright/mcp@latest"]
